# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
import cv2
import sys
from threading import Thread
from PyQt5 import QtCore , Qt

class Ui_Form(Qt.QWidget):
    def __init__(self):
        self.If_Camera_Open = False#判断摄像头是否里开启

    def Set_If_Camera_OpenTrue(self):
        self.If_Camera_Open = True
        self.out_input("停止拍照")

    def out_input(self , out):
        self.listView_2.insertPlainText(out+"\n")
                #布局
#水平布局:horizontalLayout      垂直布局:verticalLayout

    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1310, 608)
        self.verticalLayout_8 = Qt.QVBoxLayout(Form)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.horizontalLayout_7 = Qt.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")

        self.verticalLayout = Qt.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = Qt.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")

        self.label = Qt.QLabel(Form)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)

        self.comboBox = Qt.QComboBox(Form)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.horizontalLayout.addWidget(self.comboBox)
        self.pushButton = Qt.QPushButton(Form)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout.addWidget(self.pushButton)
        self.label_2 = Qt.QLabel(Form)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.comboBox_2 = Qt.QComboBox(Form)
        self.comboBox_2.setObjectName("comboBox_2")
        self.comboBox_2.addItem("")

        self.horizontalLayout.addWidget(self.comboBox_2)
        self.pushButton_2 = Qt.QPushButton(Form)
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout.addWidget(self.pushButton_2)
        self.pushButton_3 = Qt.QPushButton(Form)
        self.pushButton_3.setObjectName("pushButton_3")
        self.horizontalLayout.addWidget(self.pushButton_3)
        self.pushButton_4 = Qt.QPushButton(Form)
        self.pushButton_4.setObjectName("pushButton_4")
        self.horizontalLayout.addWidget(self.pushButton_4)
        self.pushButton_5 = Qt.QPushButton(Form)
        self.pushButton_5.setObjectName("pushButton_5")
        self.horizontalLayout.addWidget(self.pushButton_5)
        self.pushButton_6 = Qt.QPushButton(Form)
        self.pushButton_6.setObjectName("pushButton_6")
        self.horizontalLayout.addWidget(self.pushButton_6)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.listView = Qt.QLabel(Form)
        self.listView.setObjectName("listView")
        self.verticalLayout.addWidget(self.listView)
        self.horizontalLayout_7.addLayout(self.verticalLayout)
        self.verticalLayout_7 = Qt.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.horizontalLayout_2 = Qt.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.pushButton_7 = Qt.QPushButton(Form)
        self.pushButton_7.setObjectName("pushButton_7")
        self.horizontalLayout_2.addWidget(self.pushButton_7)
        self.pushButton_8 = Qt.QPushButton(Form)
        self.pushButton_8.setObjectName("pushButton_8")
        self.horizontalLayout_2.addWidget(self.pushButton_8)
        self.pushButton_9 = Qt.QPushButton(Form)
        self.pushButton_9.setObjectName("pushButton_9")
        self.horizontalLayout_2.addWidget(self.pushButton_9)
        self.verticalLayout_7.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = Qt.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_3 = Qt.QLabel(Form)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_3.addWidget(self.label_3)
        self.pushButton_10 = Qt.QPushButton(Form)
        self.pushButton_10.setObjectName("pushButton_10")
        self.horizontalLayout_3.addWidget(self.pushButton_10)
        self.pushButton_11 = Qt.QPushButton(Form)
        self.pushButton_11.setObjectName("pushButton_11")
        self.horizontalLayout_3.addWidget(self.pushButton_11)
        self.verticalLayout_7.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_5 = Qt.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.verticalLayout_2 = Qt.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_4 = Qt.QLabel(Form)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_2.addWidget(self.label_4)
        self.label_5 = Qt.QLabel(Form)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_2.addWidget(self.label_5)
        self.label_6 = Qt.QLabel(Form)
        self.label_6.setObjectName("label_6")
        self.verticalLayout_2.addWidget(self.label_6)
        self.label_7 = Qt.QLabel(Form)
        self.label_7.setObjectName("label_7")
        self.verticalLayout_2.addWidget(self.label_7)
        self.horizontalLayout_5.addLayout(self.verticalLayout_2)
        self.verticalLayout_3 = Qt.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.spinBox = Qt.QSpinBox(Form)
        self.spinBox.setObjectName("spinBox")
        self.verticalLayout_3.addWidget(self.spinBox)
        self.spinBox_2 = Qt.QSpinBox(Form)
        self.spinBox_2.setObjectName("spinBox_2")
        self.verticalLayout_3.addWidget(self.spinBox_2)
        self.spinBox_3 = Qt.QSpinBox(Form)
        self.spinBox_3.setObjectName("spinBox_3")
        self.verticalLayout_3.addWidget(self.spinBox_3)
        self.spinBox_4 = Qt.QSpinBox(Form)
        self.spinBox_4.setObjectName("spinBox_4")
        self.verticalLayout_3.addWidget(self.spinBox_4)
        self.horizontalLayout_5.addLayout(self.verticalLayout_3)
        self.verticalLayout_7.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_4 = Qt.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_8 = Qt.QLabel(Form)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_4.addWidget(self.label_8)
        self.pushButton_12 = Qt.QPushButton(Form)
        self.pushButton_12.setObjectName("pushButton_12")
        self.horizontalLayout_4.addWidget(self.pushButton_12)
        self.pushButton_13 = Qt.QPushButton(Form)
        self.pushButton_13.setObjectName("pushButton_13")
        self.horizontalLayout_4.addWidget(self.pushButton_13)
        self.verticalLayout_7.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_6 = Qt.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.verticalLayout_4 = Qt.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_9 = Qt.QLabel(Form)
        self.label_9.setObjectName("label_9")
        self.verticalLayout_4.addWidget(self.label_9)
        self.label_10 = Qt.QLabel(Form)
        self.label_10.setObjectName("label_10")
        self.verticalLayout_4.addWidget(self.label_10)
        self.label_11 = Qt.QLabel(Form)
        self.label_11.setObjectName("label_11")
        self.verticalLayout_4.addWidget(self.label_11)
        self.label_12 = Qt.QLabel(Form)
        self.label_12.setObjectName("label_12")
        self.verticalLayout_4.addWidget(self.label_12)
        self.label_13 = Qt.QLabel(Form)
        self.label_13.setObjectName("label_13")
        self.verticalLayout_4.addWidget(self.label_13)
        self.git = Qt.QMovie("./load.gif")
        self.label_14 = Qt.QLabel(Form)
        self.label_14.setObjectName("label_14")
        self.verticalLayout_4.addWidget(self.label_14)
        self.label_15 = Qt.QLabel(Form)
        self.label_15.setObjectName("label_15")
        self.verticalLayout_4.addWidget(self.label_15)
        self.label_16 = Qt.QLabel(Form)
        self.label_16.setObjectName("label_16")
        self.verticalLayout_4.addWidget(self.label_16)
        self.horizontalLayout_6.addLayout(self.verticalLayout_4)
        self.verticalLayout_5 = Qt.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.spinBox_5 = Qt.QSpinBox(Form)
        self.spinBox_5.setObjectName("spinBox_5")
        self.verticalLayout_5.addWidget(self.spinBox_5)
        self.spinBox_6 = Qt.QSpinBox(Form)
        self.spinBox_6.setObjectName("spinBox_6")
        self.verticalLayout_5.addWidget(self.spinBox_6)
        self.spinBox_7 = Qt.QSpinBox(Form)
        self.spinBox_7.setObjectName("spinBox_7")
        self.verticalLayout_5.addWidget(self.spinBox_7)
        self.spinBox_8 = Qt.QSpinBox(Form)
        self.spinBox_8.setObjectName("spinBox_8")
        self.verticalLayout_5.addWidget(self.spinBox_8)
        self.spinBox_9 = Qt.QSpinBox(Form)
        self.spinBox_9.setObjectName("spinBox_9")
        self.verticalLayout_5.addWidget(self.spinBox_9)
        self.spinBox_10 = Qt.QSpinBox(Form)
        self.spinBox_10.setObjectName("spinBox_10")
        self.verticalLayout_5.addWidget(self.spinBox_10)
        self.spinBox_11 = Qt.QSpinBox(Form)
        self.spinBox_11.setObjectName("spinBox_11")
        self.verticalLayout_5.addWidget(self.spinBox_11)
        self.spinBox_12 = Qt.QSpinBox(Form)
        self.spinBox_12.setObjectName("spinBox_12")
        self.verticalLayout_5.addWidget(self.spinBox_12)
        self.horizontalLayout_6.addLayout(self.verticalLayout_5)
        self.verticalLayout_7.addLayout(self.horizontalLayout_6)
        self.verticalLayout_6 = Qt.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.label_17 = Qt.QLabel(Form)
        self.label_17.setObjectName("label_17")
        self.verticalLayout_6.addWidget(self.label_17)
        self.listView_2 = Qt.QTextEdit(Form)
        self.listView_2.setObjectName("listView_2")
        self.verticalLayout_6.addWidget(self.listView_2)
        self.pushButton_14 = Qt.QPushButton(Form)
        self.pushButton_14.setObjectName("pushButton_14")
        self.verticalLayout_6.addWidget(self.pushButton_14)
        self.verticalLayout_7.addLayout(self.verticalLayout_6)
        self.horizontalLayout_7.addLayout(self.verticalLayout_7)
        self.verticalLayout_8.addLayout(self.horizontalLayout_7)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)



    def load_camera(self):
        self.listView.setMovie(self.git)
        self.git.start()
        self.listView.setScaledContents(True)
        self.out_input("开始")

        Thread(target=self.video_demo ).start()

    def video_demo(self):
        self.If_Camera_Open = False
        # 0是代表摄像头编号，只有一个的话默认为0
        cap = cv2.VideoCapture(0)
        # 设置显示分辨率和FPS ,不设置的话会非常卡
        cap.set(cv2.CAP_PROP_FRAME_WIDTH, 1080)
        cap.set(cv2.CAP_PROP_FRAME_HEIGHT, 720)
        cap.set(cv2.CAP_PROP_FPS, 30)
        while cap.isOpened():
            ret, frame = cap.read()
            if self.If_Camera_Open:
                return
            if ret == False:
                continue
            # 水平翻转,很有必要
            frame = cv2.flip(frame, 1)
            # opencv 默认图像格式是rgb qimage要使用BRG,这里进行格式转换,不用这个的话,图像就变色了,困扰了半天,翻了一堆资料
            frame = cv2.cvtColor(frame, cv2.COLOR_RGB2BGR)
            # mat-->qimage
            img= Qt.QImage(frame.data, frame.shape[1], frame.shape[0], Qt.QImage.Format_RGB888)
            self.listView.setPixmap(Qt.QPixmap.fromImage(img))



#label便签
#pushButton按钮
#comboBox可选着按钮
#addItems 给可选着按钮的附加项
    #上面的对应布局改名字
    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText("ModBus端口")
        self.comboBox.setItemText(0, "/dev/tty50")
        self.comboBox.addItems(['aa' , "a"])
        self.pushButton.setText(_translate("Form", "连接ModBus"))
        self.label_2.setText(_translate("Form", "机器人端口"))
        self.comboBox_2.setItemText(0, _translate("Form", "/dev/tty50"))
        self.pushButton_2.setText(_translate("Form", "连接机器人"))
        self.pushButton_3.setText(_translate("Form", "模拟取件"))
        self.pushButton_4.setText(_translate("Form", "连接摄像头"))
        self.pushButton_4.clicked.connect(lambda : self.load_camera())

        self.pushButton_5.setText(_translate("Form", "拍照"))
        self.pushButton_5.clicked.connect(lambda : self.out_input("拍照"))
        self.pushButton_6.setText(_translate("Form", "拍照并检测"))
        self.pushButton_6.clicked.connect(lambda : self.out_input("拍照并检测"))
        self.pushButton_7.setText(_translate("Form", "开始"))
        self.pushButton_7.clicked.connect(lambda : self.load_camera())
        self.pushButton_8.setText(_translate("Form", "停止"))
        self.pushButton_8.clicked.connect(lambda : self.Set_If_Camera_OpenTrue())
        self.pushButton_9.setText(_translate("Form", "退出程序"))
        self.pushButton_9.clicked.connect(Qt.QCoreApplication.instance().quit)

        self.label_3.setText(_translate("Form", "机器人状态"))
        self.pushButton_10.setText(_translate("Form", "读取"))
        self.pushButton_11.setText(_translate("Form", "设置"))
        self.label_4.setText(_translate("Form", "x="))
        self.label_5.setText(_translate("Form", "y="))
        self.label_6.setText(_translate("Form", "z="))
        self.label_7.setText(_translate("Form", "r="))
        self.label_8.setText(_translate("Form", "ModBus IO"))
        self.pushButton_12.setText(_translate("Form", "读取"))
        self.pushButton_13.setText(_translate("Form", "设置"))
        self.label_9.setText(_translate("Form", "7="))
        self.label_10.setText(_translate("Form", "6="))
        self.label_11.setText(_translate("Form", "5="))
        self.label_12.setText(_translate("Form", "4="))
        self.label_13.setText(_translate("Form", "3="))
        self.label_14.setText(_translate("Form", "2="))
        self.label_15.setText(_translate("Form", "1="))
        self.label_16.setText(_translate("Form", "0="))
        self.label_17.setText(_translate("Form", "当前状态"))
        self.pushButton_14.setText(_translate("Form", "模拟写入数据库"))





class MessageBox(Qt.QWidget):
    def __init__(self, parent=None):
        Qt.QWidget.__init__(self, parent)
        self.w = Ui_Form()
        self.w.setupUi(self)

    def closeEvent(self, event):
        reply = Qt.QMessageBox.question(self, '提示','确定要退出吗?', Qt.QMessageBox.Yes,Qt.QMessageBox.No)
        if reply == Qt.QMessageBox.Yes:
            event.accept()
            self.w.If_Camera_Open = True
        else:
            event.ignore()

if __name__ == '__main__':
    app = Qt.QApplication(sys.argv)
    form = MessageBox()
    form.show()
    sys.exit(app.exec_())
